# Runs the Pytest test suite when PRs are made against any branch

name: Run Pytest via Docker Compose on all PRs

on:
    pull_request:
      branches:
        - "*"
    push:
      branches:
        - development
        - staging
        - live

jobs:
  build-and-run-pytest-suite-in-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from repo secrets
        run: |
          echo -e "${{ secrets.ENVIRONMENT }}" | base64 -d > envs/.env
          cat envs/.env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Show Docker environment info
        run: |
          docker compose config

      - name: Build Docker images and run containers with compose
        run: |
          docker compose up -d

      - name: Run tests
        run: |
          docker compose exec django pytest -v



